
server:
  port: 8089
#  servlet:
#    context-path: /thinker
spring:
  profiles:
    active: dev
  application:
    name: thinker
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        file-extension: yaml


feign:
  sentinel:
    enabled: true

#hystrix的超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000
#        timeout:
#          enabled: true
#  threadpool:
#    default:
#      maxQueueSize: 20
#      maximumSize: 20
#      queueSizeRejectionThreshold: 20
#      allowMaximumSizeToDivergeFromCoreSize: true

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 10000
  MaxAutoRetries: 0 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试
  ServerListRefreshInterval: 5000 #eureka客户端ribbon刷新时间,默认30s

info:
  app.name: thinker
  company.name: br
  build.artifactId: $project.artifactId$
  build.version: $project.version$
