server:
  port: 8089
  servlet:
    context-path: /thinker

spring:
  application:
    name: thinker

feign: 
  hystrix:
    enabled: true

eureka:
  client:
    #eureka client刷新本地缓存时间,默认30s
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    service-url: 
      defaultZone: http://192.168.180.10:8761/eureka/


#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
        timeout:
          enabled: true
  threadpool:
    default:
      maxQueueSize: 20
      maximumSize: 20


ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 30000
  MaxAutoRetries: 0 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试
  ServerListRefreshInterval: 5000 #eureka客户端ribbon刷新时间,默认30s

info:
  app.name: thinker
  company.name: br
  build.artifactId: $project.artifactId$
  build.version: $project.version$
