server:
  port: 9002

spring:
  application:
    name: gateway-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: springcloud-gateway-zuul
    prefer-ip-address: true


zuul:
  #ignored-services: thinker
  prefix: /api
  ignored-services: "*"
  routes:
#    thinker: /thinker-proxy/**
#    show-demo: /show-proxy/**
    thinker.path: /thinker-proxy/**
    thinker.serviceId: thinker
    show.path: /show-proxy/**
    show.serviceId: show-demo


ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 3000
  SocketTimeout: 15000
  eager-load:
    clients: show-demo, thinker
    enabled: true #开启Ribbon的饥饿加载模式


info:
  app.name: springcloud-gateway-zuul
  company.name: br
  build.artifactId: $project.artifactId$
  build.version: $project.version$

